// Given a raster path under /public (.jpeg/.jpg/.png), return the sibling
// avif/webp sources generated by scripts/optimize-images.mjs plus the original
// fallback, for use in a <picture> element.
export interface PictureSources {
	avif: string;
	webp: string;
	fallback: string;
}

export const pictureSources = (src: string): PictureSources => {
	const base = src.replace(/\.(png|jpe?g)$/i, "");
	return {
		avif: `${base}.avif`,
		webp: `${base}.webp`,
		fallback: src,
	};
};
